#!/bin/bash
#Menu
clear
echo -e "\e[1;33m==============================================================="
echo -e "\e[1;36m                    AutoScriptVPS by  Badboy                   "
echo -e "\e[1;36m                           Redfox VPN                          "
echo -e "\e[1;33m==============================================================="
echo -e "\e[1;33m=============================\e[1;36m[Menu]\e[1;33m============================="
echo -e "\e[1;32m* menu         : \e[1;34mList of Main Commands"
echo -e "\e[1;32m"
echo -e "\e[1;33m=========================\e[1;36m[SSH & OpenVPN]\e[1;33m========================"
echo -e "\e[1;32m* usernew      : \e[1;34mBuat Account SSH dan OpenVPN"
echo -e "\e[1;32m* trial        : \e[1;34mBuat Trial Account SSH dan OpenVPN"
echo -e "\e[1;32m* renew        : \e[1;34mRenew Account SSH & OpenVPN"
echo -e "\e[1;32m* deluser      : \e[1;34mPadam Account SSH dan OpenVPN"
echo -e "\e[1;32m* member       : \e[1;34mList Account SSH dan OpenVPN"
echo -e "\e[1;32m* delete       : \e[1;34mPadam Account SSH dan OpenVPN yang sudah expired"
echo -e "\e[1;32m* autokill     : \e[1;34mSet up Autokill SSH"
echo -e "\e[1;32m* ceklim       : \e[1;34mTampilkan Multi Login SSH"
echo -e "\e[1;32m* restart      : \e[1;34mRestart Dropbear, Webmin, Squid3,"
echo -e "\e[1;32m                 \e[1;34mOpenVPN dan SSH"
echo -e "\e[1;32m"
echo -e "\e[1;33m===========================\e[1;36m[Wireguard]\e[1;33m========================="
echo -e "\e[1;32m* addwg        : \e[1;34mBuat Account Wireguard"
echo -e "\e[1;32m* delwg        : \e[1;34mPadam Account Wireguard"
echo -e "\e[1;32m* renewwg      : \e[1;34mRenew Account Wireguard"
echo -e "\e[1;32m* wg show      : \e[1;34mCek Wireguard"
echo -e "\e[1;32m"
echo -e "\e[1;33m==========================\e[1;36m[L2TP/IPSEC]\e[1;33m========================="
echo -e "\e[1;32m* addl2tp      : \e[1;34mBuat Account L2TP / IPSEC"
echo -e "\e[1;32m* dell2tp      : \e[1;34mPadam L2TP / IPSEC"
echo -e "\e[1;32m* renewl2tp    : \e[1;34mRenew L2TP / IPSEC"
echo -e "\e[1;32m"
echo -e "\e[1;33m=============================\e[1;36m[PPTP]\e[1;33m============================"
echo -e "\e[1;32m* addpptp      : \e[1;34mBuat Account PPTP"
echo -e "\e[1;32m* delpptp      : \e[1;34m Account PPTP"
echo -e "\e[1;32m* renewpptp    : \e[1;34mRenew Account PPTP"
echo -e "\e[1;32m"
echo -e "\e[1;33m=============================\e[1;36m[SSTP]\e[1;33m============================"
echo -e "\e[1;32m* addsstp      : \e[1;34mBuat Account SSTP"
echo -e "\e[1;32m* delsstp      : \e[1;34mPadam AccountSSTP"
echo -e "\e[1;32m* renewsstp    : \e[1;34mRenew Account SSTP"
echo -e "\e[1;32m"
echo -e "\e[1;33m=============================\e[1;36m[SSR]\e[1;33m============================="
echo -e "\e[1;32m* addssr       : \e[1;34mBuat Account shadowsocks-R"
echo -e "\e[1;32m* delssr       : \e[1;34mPadam Account shadowsocks-R"
echo -e "\e[1;32m* renewssr     : \e[1;34mRenew Account shadowsocks-R"
echo -e "\e[1;32m* ssr          : \e[1;34mTampilkan menu shadowsocks-R lainnya"
echo -e "\e[1;32m"
echo -e "\e[1;33m========================\e[1;36m[Shadowsocks OBFS]\e[1;33m====================="
echo -e "\e[1;32m* addss        : \e[1;34mBuat Account shadowsocks"
echo -e "\e[1;32m* delss        : \e[1;34mPadam Account shadowsocks"
echo -e "\e[1;32m* renewss      : \e[1;34mRenew Account shadowsocks"
echo -e "\e[1;32m"
echo -e "\e[1;33m=============================\e[1;36m[V2RAY]\e[1;33m==========================="
echo -e "\e[1;32m* addws        : \e[1;34mBuat Account vmess"
echo -e "\e[1;32m* delws        : \e[1;34mPadam Account vmess"
echo -e "\e[1;32m* renewws      : \e[1;34mRenew Account vmess"
echo -e "\e[1;32m* certv2ray    : \e[1;34mRenew serifikat vmess"
echo -e "\e[1;32m"
echo -e "\e[1;33m=============================\e[1;36m[VLESS]\e[1;33m==========================="
echo -e "\e[1;32m* addvless     : \e[1;34mBuat Account vless"
echo -e "\e[1;32m* delvless     : \e[1;34mPadam Account vless"
echo -e "\e[1;32m* renewvless   : \e[1;34mRenew Account vless"
echo -e "\e[1;32m"
echo -e "\e[1;33m=============================\e[1;36m[Trojan]\e[1;33m=========================="
echo -e "\e[1;32m* addtr        : \e[1;34mBuat Account trojan"
echo -e "\e[1;32m* deltr        : \e[1;34mPadam Account trojan"
echo -e "\e[1;32m* renewtr      : \e[1;34mRenew Account trojan"
echo -e "\e[1;32m"
echo -e "\e[1;33m=============================\e[1;36m[SYSTEM]\e[1;33m=========================="
echo -e "\e[1;32m* addhost      : \e[1;34mBuat Subdomain/Pointing Bug"
echo -e "\e[1;32m* webmin       : \e[1;34mTampilkan menu webmin"
echo -e "\e[1;32m* ram          : \e[1;34mCek Penggunaan ram VPS"
echo -e "\e[1;32m* reboot       : \e[1;34mReboot VPS"
echo -e "\e[1;32m* speedtest    : \e[1;34mTes kecepatan VPS"
echo -e "\e[1;32m* info         : \e[1;34mInformasi"
echo -e "\e[1;32m* about        : \e[1;34mInformasi script autossh"
echo -e "\e[1;32m"
echo -e "\e[1;33m==============================================================="
echo -e "\e[1;32m"
